//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZarlokEntities1 : DbContext
    {
        public ZarlokEntities1()
            : base("name=ZarlokEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<test> test { get; set; }
        public virtual DbSet<Achievement> Achievement { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Eaten> Eaten { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<Friendship> Friendship { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<ProfileAchievement> ProfileAchievement { get; set; }
        public virtual DbSet<Request> Request { get; set; }
    }
}
