//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarlokMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identifier
    {
        public int id { get; set; }
        public string keyIdentifer { get; set; }
        public Nullable<int> profileId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
