//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarlokMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Eaten = new HashSet<Eaten>();
            this.ProfileAchievement = new HashSet<ProfileAchievement>();
            this.Identifier = new HashSet<Identifier>();
            this.Friendship = new HashSet<Friendship>();
            this.Friendship1 = new HashSet<Friendship>();
            this.Request = new HashSet<Request>();
            this.Request1 = new HashSet<Request>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<Eaten> Eaten { get; set; }
        public virtual ICollection<ProfileAchievement> ProfileAchievement { get; set; }
        public virtual ICollection<Identifier> Identifier { get; set; }
        public virtual ICollection<Friendship> Friendship { get; set; }
        public virtual ICollection<Friendship> Friendship1 { get; set; }
        public virtual ICollection<Request> Request { get; set; }
        public virtual ICollection<Request> Request1 { get; set; }
    }
}
