//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarlokMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZarlokEntities : DbContext
    {
        public ZarlokEntities()
            : base("name=ZarlokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Achievement> Achievement { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Eaten> Eaten { get; set; }
        public DbSet<Food> Food { get; set; }
        public DbSet<Profile> Profile { get; set; }
        public DbSet<ProfileAchievement> ProfileAchievement { get; set; }
        public DbSet<Identifier> Identifier { get; set; }
        public DbSet<Friendship> Friendship { get; set; }
        public DbSet<Request> Request { get; set; }
    }
}
